# Generated by Django 5.1.3 on 2024-12-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.IntegerField(choices=[(1, 'Вода'), (2, 'Канализация')])),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')])),
                ('completed_works', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('volume', models.FloatField()),
                ('summ', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeverageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_works', models.CharField(max_length=255)),
                ('january_vol', models.FloatField(blank=True, null=True)),
                ('january_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('february_vol', models.FloatField(blank=True, null=True)),
                ('february_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('march_vol', models.FloatField(blank=True, null=True)),
                ('march_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('first_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('april_vol', models.FloatField(blank=True, null=True)),
                ('april_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('may_vol', models.FloatField(blank=True, null=True)),
                ('may_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('june_vol', models.FloatField(blank=True, null=True)),
                ('june_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('second_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('july_vol', models.FloatField(blank=True, null=True)),
                ('july_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('august_vol', models.FloatField(blank=True, null=True)),
                ('august_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('september_vol', models.FloatField(blank=True, null=True)),
                ('september_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('third_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('october_vol', models.FloatField(blank=True, null=True)),
                ('october_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('november_vol', models.FloatField(blank=True, null=True)),
                ('november_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('december_vol', models.FloatField(blank=True, null=True)),
                ('december_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fourth_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('year_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_works', models.CharField(max_length=255)),
                ('january_vol', models.FloatField(blank=True, null=True)),
                ('january_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('february_vol', models.FloatField(blank=True, null=True)),
                ('february_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('march_vol', models.FloatField(blank=True, null=True)),
                ('march_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('first_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('april_vol', models.FloatField(blank=True, null=True)),
                ('april_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('may_vol', models.FloatField(blank=True, null=True)),
                ('may_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('june_vol', models.FloatField(blank=True, null=True)),
                ('june_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('second_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('july_vol', models.FloatField(blank=True, null=True)),
                ('july_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('august_vol', models.FloatField(blank=True, null=True)),
                ('august_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('september_vol', models.FloatField(blank=True, null=True)),
                ('september_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('third_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('october_vol', models.FloatField(blank=True, null=True)),
                ('october_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('november_vol', models.FloatField(blank=True, null=True)),
                ('november_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('december_vol', models.FloatField(blank=True, null=True)),
                ('december_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fourth_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('year_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
