# Generated by Django 5.1.3 on 2024-12-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembaza_app', '0002_alter_severagetable_april_summ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthworks',
            name='summ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='monthworks',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='april_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='august_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='december_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='february_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='january_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='july_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='june_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='march_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='may_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='november_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='october_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='severagetable',
            name='september_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='april_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='august_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='december_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='february_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='january_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='july_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='june_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='march_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='may_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='november_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='october_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='september_vol',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
