# Generated by Django 5.1.3 on 2024-12-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembaza_app', '0003_alter_monthworks_summ_alter_monthworks_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthworks',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024),
        ),
        migrations.AddField(
            model_name='severagetable',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024),
        ),
        migrations.AddField(
            model_name='watertable',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024),
        ),
    ]
